# Generated by Django 5.2.6 on 2025-10-05 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость услуги')),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, max_length=150, verbose_name='Описание услуги')),
            ],
            options={
                'ordering': ['title', 'price'],
            },
        ),
    ]
