# Generated by Django 5.2.6 on 2025-09-21 11:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название рекламной компании')),
                ('promotion_channel', models.PositiveSmallIntegerField(choices=[(1, 'Site'), (2, 'Social Network'), (3, 'Integration')], default=1, verbose_name='Канал продвижения')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бюджет')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertising', to='products.product')),
            ],
        ),
    ]
