# Generated by Django 5.2.6 on 2025-10-03 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_companies', '0001_initial'),
        ('products', '0002_alter_product_description_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertising', to='products.product', verbose_name='Услуга'),
        ),
    ]
