# Generated by Django 5.2.6 on 2025-10-05 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Контракт')),
                ('potential_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_client', to='leads.potentialclient', verbose_name='Потенциальный клиент')),
            ],
        ),
    ]
