# Generated by Django 5.2.6 on 2025-09-24 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_companies', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeclient',
            name='advertising',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='active_clients', to='advertising_companies.advertising'),
        ),
    ]
