# Generated by Django 5.2.6 on 2025-10-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_rename_sum_contract_cost'),
        ('customers', '0002_activeclient_advertising'),
        ('leads', '0005_alter_potentialclient_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeclient',
            name='advertising',
        ),
        migrations.AlterField(
            model_name='activeclient',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Контракт'),
        ),
        migrations.AlterField(
            model_name='activeclient',
            name='potential_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.potentialclient', verbose_name='Потенциальный клиент'),
        ),
    ]
