# Generated by Django 5.2.6 on 2025-10-03 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_activeclient_advertising_and_more'),
        ('leads', '0006_alter_potentialclient_advertising_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeclient',
            name='potential_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_client', to='leads.potentialclient', verbose_name='Потенциальный клиент'),
        ),
    ]
