# Generated by Django 5.2.6 on 2025-10-05 12:27

import contracts.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название контракта')),
                ('document', models.FileField(upload_to=contracts.models.contract_document_directory_path, verbose_name='Документ')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость контракта')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Начало действия')),
                ('end_date', models.DateTimeField(verbose_name='Конец действия')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='products.product', verbose_name='Услуга')),
            ],
        ),
    ]
