# Generated by Django 5.2.6 on 2025-09-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_service'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='products.product'),
        ),
    ]
