# Generated by Django 5.2.6 on 2025-09-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='sum',
            new_name='cost',
        ),
    ]
