# Generated by Django 5.2.6 on 2025-10-03 09:00

import contracts.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_rename_sum_contract_cost'),
        ('products', '0002_alter_product_description_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость контракта'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(upload_to=contracts.models.contract_document_directory_path, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateTimeField(verbose_name='Конец действия'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='products.product', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начало действия'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Название контракта'),
        ),
    ]
