# Generated by Django 5.2.6 on 2025-10-05 12:27

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertising_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона')),
                ('advertising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_clients', to='advertising_companies.advertising', verbose_name='Рекламная компания')),
            ],
        ),
    ]
