# Generated by Django 5.2.6 on 2025-09-21 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertising_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Номер телефона')),
                ('advertising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_clients', to='advertising_companies.advertising')),
            ],
        ),
    ]
