# Generated by Django 5.2.6 on 2025-09-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialclient',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Полное имя'),
        ),
    ]
