# Generated by Django 5.2.6 on 2025-09-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_potentialclient_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potentialclient',
            old_name='full_name',
            new_name='last_name',
        ),
    ]
