# Generated by Django 5.2.6 on 2025-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_rename_full_name_potentialclient_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Фамилия'),
        ),
    ]
