# Generated by Django 5.2.6 on 2025-10-03 08:06

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_potentialclient_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
