# Generated by Django 5.2.6 on 2025-10-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_companies', '0001_initial'),
        ('leads', '0005_alter_potentialclient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='advertising',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_clients', to='advertising_companies.advertising', verbose_name='Рекламная компания'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
